### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'dilation'

### ISSUE THREAD

**Issue by mathigatti** [Hhhhhhhhhhao/Thin-Structure-Inpainting#4]
Hi! This project looks great, I'm trying it on google colab, [here](https://colab.research.google.com/drive/10bBhjQKcQjEuthKhuwxJl-swr5zedOsy#scrollTo=wR8Jy2z3H0mW), but it's throwing an error, do you know what could be the problem?

When I run it like this
```
python train.py -c configs/road_config.json
```
It returns this
```
/usr/local/lib/python3.6/dist-packages/google/colab/data_table.py:30: UserWarning: IPython.utils.traitlets has moved to a top-level traitlets package.
  from IPython.utils import traitlets as _traitlets
Traceback (most recent call last):
  File "train.py", line 93, in <module>
    main(config, args.resume)
  File "train.py", line 24, in main
    train_data_loader = get_instance(module_data, 'train_data_loader', config)
  File "train.py", line 17, in get_instance
    return getattr(module, config[name]['type'])(*args, **config[name]['args'])
TypeError: __init__() got an unexpected keyword argument 'dilation'
```

I'm running it over a [fork of your project](https://github.com/mathigatti/Thin-Structure-Inpainting/tree/master/data/Road) which is pretty much like the original code but with a few test images in the data/Road folder.

Thanks again for sharing this :)

**Comment by Hhhhhhhhhhao** [comment]
Hi,

The problem is caused by the parameter set in the road config file.

For road dataloader (and other dataloaders exceppt for the root one), there is no signature about dilation, you can check dataloader file about this.

I have removed these parameters from config file.
